// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Mirror Next.js env precedence so Prisma CLI commands (migrate deploy, etc.)
// pick up DATABASE_URL even when it lives in .env.local. dotenv never
// overrides variables already present in process.env, so real OS env wins,
// then .env.local, then .env.
loadEnv({ path: ".env.local" });
loadEnv({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});

